#!/usr/bin/env bash
# Script to configure an Ubuntu server with Nginx, a custom 404 page, and a custom response header:
sudo apt-get update -y
sudo apt-get install -y nginx
sudo ufw allow "Nginx HTTP"

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

newlines=$'\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}'

sudo sed -i "27i $newlines" /etc/nginx/sites-available/default


HOSTNAME=$(hostname)

sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

sudo systemctl restart nginx

