#!/usr/bin/env bash
# Install Nginx and configure custom header

# Set hostname
if [[ $(hostname) == "ubuntu" ]]; then
  sudo hostnamectl set-hostname "6383-$(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
fi

# Update system and install Nginx
sudo apt update -y
sudo apt install -y nginx

# Add the custom header to track which server is responding
sudo sed -i "47i\\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
