#!/usr/bin/env bash
# Script to configure an Ubuntu server with Nginx and a custom response header

# Update and install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Get the hostname of the server
HOSTNAME=$(hostname)

# Modify the Nginx configuration to add the X-Served-By header
sudo sed -i "47i\\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

