#!/usr/bin/env bash
# Script that installs Nginx server, configures a custom 404 page

# Update and install nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Allow Nginx through firewall
sudo ufw allow "Nginx HTTP"

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html > /dev/null

# Modify Nginx default site configuration
sudo sed -i '/server_name _;/a \    error_page 404 /404.html;\n    location = /404.html {\n        root /usr/share/nginx/html;\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

